name: gpgLabs-environment

channels:
  - conda-forge
  - gimli
  - defaults
dependencies:
  - numpy
  - scipy
  - 'matplotlib < 3.0.0'
  - pygimli
  - pip:
    - git+https://github.com/simpeg/geoana
    - git+https://github.com/geoscixyz/gpgLabs
