name: gpgLabs-environment

channels:
  - conda-forge
  - gimli
  #- defaults
dependencies:
  - numpy
  - scipy
  - matplotlib=3.4.3
  - pygimli=1.4.3
  - pip:
    - git+https://github.com/simpeg/geoana
    - git+https://github.com/geoscixyz/geosci-labs
